# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: root
  timeout: 5000

development:
  <<: *default
  database: poc_development

test:
  <<: *default
  database: poc_test

production:
  <<: *default
  database: poc_production
